services:
  - type: web
    name: backend
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
